VIA_ENABLE = yes
CAPS_WORD_ENABLE = yes
LAYER_LOCK_ENABLE = yes
CONSOLE_ENABLE = yes

USER_NAME = uk-taniyama
LIB_TRANSLATE_JP_ENABLE = yes
LIB_DEFAULT_LAYER_TOGGLE_ENABLE = yes
LIB_RGBLIGHT_LAYER_COLOR_ENABLE = yes
