UK_TANIYAMA_LIBS_DIR = $(TOP_DIR)/keyboards/uk-taniyama/libs
OPT_DEFS += -I$(UK_TANIYAMA_LIBS_DIR)

ifeq ($(LIB_TRANSLATE_JP_ENABLE),yes)
    SRC += $(UK_TANIYAMA_LIBS_DIR)/translate_jp.c
    OPT_DEFS += -DLIB_TRANSLATE_JP_ENABLE
endif
ifeq ($(LIB_DEFAULT_LAYER_TOGGLE_ENABLE),yes)
    SRC += $(UK_TANIYAMA_LIBS_DIR)/default_layer_toggle.c
    OPT_DEFS += -DLIB_DEFAULT_LAYER_TOGGLE_ENABLE
endif
ifeq ($(LIB_RGBLIGHT_LAYER_COLOR_ENABLE),yes)
    SRC += $(UK_TANIYAMA_LIBS_DIR)/rgblight_layer_color.c
    OPT_DEFS += -DLIB_RGBLIGHT_LAYER_COLOR_ENABLE
endif
